language: node_js
node_js:
  - "0.12"
notifications:
  email: false
after_success:
  - chmod 600 .travis/deploy_key.pem
  - ssh-add .travis/deploy_key.pem
  - git remote add deploy git@github.com:Faverick/trendets.git
  - git push deploy feature/travis-ci_TD-21
