language: node_js
node_js:
- '0.12'
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_ca96f6bc6cbe_key -iv $encrypted_ca96f6bc6cbe_iv
  -in .travis/id_rsa.enc -out ~\/.ssh/id_rsa -d
after_success:
- git remote add deploy git@github.com:Faverick/trendets.git
- git add doc/*
- git commit -am "Documentation updated"
- git push deploy feature/travis-ci_TD-21
