language: node_js
node_js:
- '0.12'
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_ca96f6bc6cbe_key -iv $encrypted_ca96f6bc6cbe_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
before_script:
- git config --global user.email "a.a.pakhomoff@gmail.com"
- git config --global user.name "Travis-CI"
after_success:
- chmod 600 ~/.ssh/id_rsa
- eval "$(ssh-agent)"
- ssh-add
- git remote add deploy git@github.com:Faverick/trendets.git
- git add doc/*
- git stash
- git checkout documentation
- git rm -rf doc/*
- git stash apply
- git stash clear
- git commit -m "Documentation updated"
- git push deploy documentation
