language: node_js
node_js:
  - "0.12"
notifications:
  email: false
after_success:
  - > .travis/deploy_key.pem
  - chmod 600 .travis/deploy_key.pem
  - ssh-add .travis/deploy_key.pem
  - git remote add deploy https://github.com/Faverick/trendets.git
  - git push deploy feature/travis-ci_TD-21